### ISSUE TITLE
Can you improve draw distance?

### ISSUE THREAD

**Issue by BIDLOV** [SuiMachine/Deadly-Premonition-2---Sui-s-hack#1]
title

**Comment by SuiMachine** [comment]
I can, but it won't help much, as the terrain is really flat. It will be noticeable in few cases, though. Will have to look into Camera Cull distance and what the game does to disable pedestrians, cause they disappear quite close to the player.

**Comment by SuiMachine** [comment]
Well - that option is exposed now, so I am going to close this now.
