### ISSUE TITLE
Strange shadow 

### ISSUE THREAD

**Issue by panchenko9b** [SuiMachine/Deadly-Premonition-2---Sui-s-hack#13]
Hello. Something that looks like a shadow moves with the character. This is noticeable only on the paved roadway, this is not observed on the sidewalk. If I change the texture resolution option to half, the shadow becomes barely visible, but distant objects, especially trees, become blurry. Is this how it should be with this setting or am I having a bug? Video for demonstration: https://youtu.be/VOa7eJwiMy4

**Comment by SuiMachine** [comment]
I think this might be because textures used for roads (whatever the opaque or transparent) seem to be entirely unfiltered, but I don't think it's possible to override (unless you replace the texture itself or extract it and build a new asset bundle with corrected settings)

**Comment by panchenko9b** [comment]
Ok, thanks for answer! So, if this is normal, you can close the issue.

**Comment by SuiMachine** [comment]
OK, so... Albedos are filtered, but normal textures, metallic textures and occlusion textures are not.... and you can override them after all in runtime via scripts, it's just - you have to do it per texture (there is no global override).

https://github.com/SuiMachine/Deadly-Premonition-2---Sui-s-hack/releases/tag/1.1.0Preview4
This should override all of those to be Trilinear filtered (with possible Anisotropic Filtering). This will however make the roads more blurry, as the texture resolution used for them is very low (and what's worse - some textures have noticeably lower pixel resolution per world unit, than textures used in neighbouring piece of road).

**Comment by panchenko9b** [comment]
Now there is no shadow. Looks good to me.
