### ISSUE TITLE
Mouse camera support not working

### ISSUE THREAD

**Issue by balloba** [SuiMachine/Deadly-Premonition-2---Sui-s-hack#18]
Hello the keyboard and mouse buttons work but i cannot control the camera. What does it mean that a modified gamemanager is required?

**Comment by SuiMachine** [comment]
There is an executable file [GlobalGameManagersPatcher.exe](https://github.com/SuiMachine/Deadly-Premonition-2---Sui-s-hack/blob/main/Release/GlobalGameManagersPatcher.exe) that you need to run, which modifies gamemanagers to handle two inputs in a way that they read Mouse Ax X and Y. You only need to run it unless Steam verifies your copy of the game.

**Comment by balloba** [comment]
That did the trick thanks. You might want to add it to the read me cause it wasn't clear
