### ISSUE TITLE
The game started to crash

### ISSUE THREAD

**Issue by BIDLOV** [SuiMachine/Deadly-Premonition-2---Sui-s-hack#3]
Now when you enter some buildings the game completely randomly crashes.

**Comment by SuiMachine** [comment]
Hmm. Maybe Unity doesn't like setting renderer bounds per instance of a model. Will have to check it.

**Comment by SuiMachine** [comment]
Does this happen on 0.6.1?
Might have been something to do with Resources.FindObjectsOfTypeAll and accidently overriding bounds of electrical poles that are not loaded into the scene. I did go back to 0.6.0 to test and it does seem like it crashes if you load the game nearby wires and then they unload and then you enter the building. I was able to get it to crash somewhat reliably on 0.6.0, but so far on 0.6.1, which uses a different method for correcting bounds - it hasn't crashed.

**Comment by BIDLOV** [comment]
> Does this happen on 0.6.1? Might have been something to do with Resources.FindObjectsOfTypeAll and accidently overriding bounds of electrical poles that are not loaded into the scene. I did go back to 0.6.0 to test and it does seem like it crashes if you load the game nearby wires and then they unload and then you enter the building. I was able to get it to crash somewhat reliably on 0.6.0, but so far on 0.6.1, which uses a different method for correcting bounds - it hasn't crashed.

Works great!
