### ISSUE TITLE
Mouse and keyboard still don't react to my pushing

### ISSUE THREAD

**Issue by alexbaker20155** [SuiMachine/Deadly-Premonition-2---Sui-s-hack#9]
Please help, i changed in cfg. file input string , launched the launcher to activate the mouse axis but the M+K don't work still, what can it be?? I can activate mod menu by pressing F11, but controls don't work, what can be the reason?

**Comment by alexbaker20155** [comment]
Maybe it's because i don't have controller plugged in?

**Comment by alexbaker20155** [comment]
Controller needs to be emulated, how to adjust sensitivity?

**Comment by SuiMachine** [comment]
Sensitivity and Y axis inversion added in 1.0.
